---
- name: Install dependencies for virtual env
  package:
    name: "{{ virtualenv_dependencies }}"
    state: present
  register: _install_venv_dep_packages
  until: _install_venv_dep_packages is succeeded
  retries: 5
  delay: 2

- name: Create CMVFS exporter virtual env and install requirements
  pip: 
    requirements: "{{ __cvmfs_virtual_env_home }}/requirements.txt"
    virtualenv: "{{ __cvmfs_virtual_env_home }}"
    virtualenv_python: "python3.6"

- name: Copy the cvmfs_exporter systemd service file
  template:
    src: "cvmfs_exporter.service.j2"
    dest: /etc/systemd/system/cvmfs_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart cvmfs_exporter

- name: Allow cvmfs_exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ cvmfs_exporter_web_listen_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"