---
- name: Install dependencies for virtual env
  yum:
    name: "python3-virtualenv"
    state: present

- name: Create CMVFS exporter virtual env and install requirements
  pip: 
    requirements: "{{ _cvmfs_virtual_env_home }}/requirements.txt"
    virtualenv: "{{ _cvmfs_virtual_env_home }}"
    virtualenv_python: "python3.6"

- name: Copy the cvmfs_exporter systemd service file
  template:
    src: cvmfs_exporter.service.j2
    dest: /etc/systemd/system/cvmfs_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart cvmfs_exporter

- name: Allow node_exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ node_exporter_web_listen_address.split(':')[-1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"